### ISSUE TITLE
High Severity Bugs: Reliability attribute

### ISSUE THREAD

**Issue by FraPCA** [Tensa53/commons-net#1]
There are 19 High Severity Bugs with the Reliability attribute, as scanned by SonarCloud. This issue is fixed by merging an appropriate pull request with all bugs fixed. Work is split between the two team members.

Two types of bugs: 17 try-with-resources without finally clause and  2 missing end conditions in loop.

**Comment by FraPCA** [comment]
https://github.com/Tensa53/commons-net/commit/70173946fbcece031118275a401bdd91005a0e94

fixes 2 of these bugs. Please let me know if there are any problems with it.

**Comment by Tensa53** [comment]
7ab5696

fixed 5 of these bugs. Keep me updated if there are any problems with them.

**Comment by FraPCA** [comment]
https://github.com/Tensa53/commons-net/commit/7b9cc39ada5f810a9d1b8571c724c9ae47086060 and https://github.com/Tensa53/commons-net/commit/1aacff807044285ca791d295b75563329423ce53

fix 8 bugs related to try-with-resources without finally clause. First commit failed build due to checkStyle violations, second fixes these.

**Comment by Tensa53** [comment]
After a further analysis of the remaining  high severity bugs related to reliability, we noticed that we couldn't use the try-with-resources statement with some bugs. As written in the Oracle Java Documentation about this type of [statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html), the resources will be closed regardless of whether the try statement completes normally or abruptly. More specifically, in the Java Specification Language related [manual](https://docs.oracle.com/javase/specs/jls/se17/html/jls-14.html#jls-14.1), the return statement is considered as an abrupt completion. Other than that, the static analysis scan by SonarCloud suggests us to fix these bugs using the try-with-resources statement  or use a finally clause to close the resources, but there are cases where we need to return the resources and we cannot close them. With the commits 3d7b59e and 93c1db5 we deciced to revert these fixes and to consider the SonarCloud suggestion as an incomplete and incorrect solution. In order to resolve these bugs, we have to find a complete and correct solution and in that case, the entire class could be involved for the fix. At the moment, we cannot allocate all the time needed for these operations because we also have other high severity bugs related to other software quality attributes, that also need to be fixed.
